import { Outfit } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';  
import "./globals.css";
import Provider from "./provider";

const outfit = Outfit({subsets:['latin']})

export const metadata = {
  title: "Adshoot AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={outfit.className}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
